# Generated by Django 5.1.2 on 2024-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
